### ISSUE TITLE
Custom node is not loading Please check  

### ISSUE THREAD

**Issue by amir84ferdos** [BlenderNeko/ComfyUI_SeeCoder#2]

**Comment by amir84ferdos** [comment]
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1725, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SeeCoder\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SeeCoder\nodes.py", line 14, in <module>
    folder_paths.folder_names_and_paths["seecoder"] = ([os.path.join(folder_paths.models_dir, "seecoders")], folder_paths.supported_ckpt_extensions)
AttributeError: module 'folder_paths' has no attribute 'supported_ckpt_extensions'

Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SeeCoder module for custom nodes: module 'folder_paths' has no attribute 'supported_ckpt_extensions'
